const data = {
  products: [
    {
      name: "Croma 592 Litres Refrigerator",
      slug: "Croma 592 Litres",
      category: "Refrigerators",
      image: "/images/CRAR2621.jpg",
      price: 230000,
      countInStock: 0,
      brand: "Croma",
      rating: 4.5,
      numReviews: 9,
      description: " Frost Free Side by Side Multi Air Flow System",
    },
    {
      name: "SAMSUNG 865 Litres Refrigerator",
      slug: "SAMSUNG 865 Litres",
      category: " Refrigerators",
      image: "/images/RF87A9770SG.jpg",
      price: 340000,
      countInStock: 11,
      brand: "Samsung",
      rating: 4.7,
      numReviews: 10,
      description:
        "Frost Free French Door Smart Wifi Enabled Refrigerator with Door-in-Door",
    },
    {
      name: "SAMSUNG Double Door Refrigerator Refrigerator",
      slug: "SAMSUNG Double Door Refrigerator Refrigerator",
      category: " Refrigerators",
      image: "/images/DoubleDoorRefrigerator.jpg",
      price: 36490.0,
      countInStock: 5,
      brand: "Samsung",
      rating: 4.8,
      numReviews: 10,
      description: "Convertible 5in1",
    },
    {
      name: "MG Hector",
      slug: "MG Hector",
      category: " Cars",
      image: "/images/mghector.jpg",
      price: 2036000,
      countInStock: 1,
      brand: "MG",
      rating: 4.5,
      numReviews: 10,
      description: "Manual/Automatic,Engine (upto)1956 cc",
    },
    {
      name: "MG Astor",
      slug: "MG Astor",
      category: " Cars",
      image: "/images/MG_Astor.jpg",
      price: 1823000,
      countInStock: 3,
      brand: "MG",
      rating: 4.7,
      numReviews: 10,
      description: "Manual/Automatic,Engine (upto)1498 cc",
    },
    {
      name: "Kia Seltos",
      slug: "Kia Seltos",
      category: " Cars",
      image: "/images/KiaSeltos.jpg",
      price: 1823000,
      countInStock: 3,
      brand: "Kia",
      rating: 4.2,
      numReviews: 10,
      description: "Mileage (upto)20.8 kmpl,Engine (upto)1497 cc",
    },
    {
      name: "Samsung 6.5 kg 5 Star",
      slug: "Samsung 6.5 kg 5 Star",
      category: " WashingMachines",
      image: "/images/Samsung6.5kg.jpg",
      price: 2949000.0,
      countInStock: 9,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 13,
      description: " Fully Automatic Front Load Washing Machine",
    },
    {
      name: "LG 10.5/7 kg 5 Star Inverter",
      slug: "LG 10.5/7 kg 5 Star Inverter",
      category: " WashingMachines",
      image: "/images/LG_Star_Inverter.jpg",
      price: 69990.0,
      countInStock: 11,
      brand: "LG",
      rating: 4.5,
      numReviews: 11,
      description: "Fully Automatic Front Load Washer Dryer",
    },
    {
      name: "Siemens 9/6 kg 5 Star",
      slug: "Siemens 9/6 kg 5 Star",
      category: " WashingMachines",
      image: "/images/Siemens_WM.jpg",
      price: 59990.0,
      countInStock: 15,
      brand: "LG",
      rating: 4.3,
      numReviews: 12,
      description: "9/6kg, Front Load, Fully Automatic,Front Load",
    },
    {
      name: "Owen Fabric Lounge Chair",
      slug: "Owen Fabric Lounge Chair",
      category: "Furniture",
      image: "/images/loungechair.jpg",
      price: 10500.0,
      countInStock: 2,
      brand: "UrbanLadder",
      rating: 4.5,
      numReviews: 12,
      description:
        "Product Dimensions : 82.0 cm x 54.0 cm x 56.0 cm,Midnight Blue Colour",
    },
    {
      name: "Owen Fabric Lounge Chair",
      slug: "Owen Fabric Lounge Chair",
      category: "Furniture",
      image: "/images/hawaiisofa.jpg",
      price: 12734.0,
      countInStock: 7,
      brand: "Wakefit",
      rating: 4.0,
      numReviews: 12,
      description: "3 Seater - Sky Green",
    },
    {
      name: "Napper Sofa",
      slug: "Napper Sofa",
      category: "Furniture",
      image: "/images/NapperSofa.jpg",
      price: 11824.0,
      countInStock: 7,
      brand: "Wakefit",
      rating: 4.1,
      numReviews: 5,
      description: "Regular, Single Seater, Cappuccino",
    },
    {
      name: "SAMSUNG 7 108 cm (43 inch) 4K Ultra HD LED",
      slug: "SAMSUNG 7 108 cm (43 inch) 4K Ultra HD LED",
      category: "Electronics",
      image: "/images/tv_samsung1.jpg",
      price: 31990.0,
      countInStock: 7,
      brand: "Samsung",
      rating: 4.6,
      numReviews: 10,
      description: "Tizen TV with Voice Assistance (2022 model)",
    },
    {
      name: "Croma 102 cm (40 inch) Full HD LED",
      slug: "Croma 102 cm (40 inch) Full HD LED",
      category: "Electronics",
      image: "/images/tv_croma1.jpg",
      price: 18990.0,
      countInStock: 7,
      brand: "Croma",
      rating: 4.6,
      numReviews: 12,
      description: "Smart Android TV with Google Assistant (2022 model)",
    },
  ],
};
export default data;
